// Parity map: every write and read the app or REST API performs → the MCP tools that cover it.
// coverage.test.ts asserts each entry names at least one registered tool.
export const coverage: Record<string, string[]> = {
  "api-jobs (GET/POST/PATCH/DELETE)": ["fetch_jobs", "create_job", "update_job", "delete_job"],
  "api-parts (GET/POST with operations/PATCH/DELETE, file-url)": ["fetch_parts", "create_part", "update_part", "delete_part", "request_part_file_upload", "attach_part_file"],
  "api-operations (GET/POST/PATCH/DELETE)": ["fetch_operations", "create_operation", "update_operation", "delete_operation"],
  "api-operation-lifecycle start/pause/resume/complete → transition_operation": ["start_operation", "pause_operation", "resume_operation", "complete_operation", "stop_operation"],
  "time_entry_action stop/pause/resume, api-time-entries": ["fetch_time_entries", "fetch_active_time_entries", "stop_time_entry", "pause_time_entry", "resume_time_entry"],
  "api-operation-quantities (report output, scrap reasons)": ["fetch_operation_quantities", "report_production", "delete_production_report"],
  "api-scrap-reasons, seed_default_scrap_reasons": ["fetch_scrap_reasons", "create_scrap_reason", "update_scrap_reason", "seed_default_scrap_reasons"],
  "api-issues (report, NCR, resolve, standstill / Yellow Card)": ["fetch_issues", "create_issue", "update_issue", "resolve_issue", "delete_issue"],
  "api-batches, api-batch-lifecycle start/stop/add-operations → transition_batch, add_batch_operations": ["fetch_batches", "create_batch", "add_batch_operations", "start_batch", "stop_batch", "update_batch", "delete_batch"],
  "api-substeps, api-templates": ["fetch_substeps", "add_substep", "complete_substep", "update_substep", "delete_substep", "fetch_substep_templates", "apply_substep_template"],
  "api-cells": ["fetch_cells", "create_cell", "update_cell", "delete_cell"],
  "api-resources, operation_resources": ["fetch_resources", "create_resource", "update_resource", "delete_resource", "assign_resource_to_operations", "unassign_resource", "check_resource_availability"],
  "api-materials": ["fetch_materials", "create_material", "update_material", "delete_material"],
  "operators: list_operators, create_operator_with_pin, reset_operator_pin, unlock_operator": ["list_operators", "create_operator", "reset_operator_pin", "unlock_operator", "update_operator"],
  "api-assignments": ["fetch_assignments", "create_assignment", "delete_assignment"],
  "factory_calendar": ["fetch_factory_calendar", "set_calendar_day", "delete_calendar_day"],
  "api-webhooks, api-webhook-deliveries, webhook_send_test, webhook_redeliver": ["fetch_webhooks", "create_webhook", "update_webhook", "delete_webhook", "fetch_webhook_deliveries", "send_test_webhook", "redeliver_webhook"],
  "tenants.feature_flags (sequentialRelease, work modes), factory hours": ["get_workshop_settings", "update_workshop_settings"],
  "activity_log": ["fetch_activity_log"],
  "notifications: create_notification, mark_notification_read": ["fetch_notifications", "create_notification", "mark_notification_read"],
  "QRM: get_cell_qrm_metrics, check_next_cell_capacity, cell capacity": ["get_cell_wip", "get_cell_capacity"],
  "locations: storage_locations, part_placements": ["fetch_storage_locations", "place_part", "remove_part_placement"],
  "routing: get_part_routing": ["get_part_routing"],
  "dashboard and analytics": ["get_dashboard_stats", "get_production_metrics", "get_scrap_analytics", "get_scrap_trends", "get_yield_metrics", "get_scrap_pareto", "get_quality_score", "get_issue_analytics", "get_issue_trends", "get_root_cause_analysis"],
  "planning": ["prioritize_job", "update_parts", "fetch_parts_by_customer", "get_job_overview", "get_parts_due_soon", "suggest_reschedule", "reschedule_operations", "complete_operations"],
};
